version: '2'
services:
  es-storage:
    image: busybox
    network_mode: none
    volumes:
    - $ES_STORAGE
    labels:
      io.rancher.container.start_once: 'true'
    command:
    - chmod
    - '777'
    - -R
    - /usr/share/elasticsearch/data
  logstash-collector-conf:
    image: alpine:latest
    working_dir: /config
    volumes:
    - /config
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    links:
    - redis:redis
    command:
    - wget
    - http://rancher-metadata.rancher.internal/latest/self/service/metadata/collector
    - -O
    - logstash.conf
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.pull_image: always
  logstash-collector:
    image: docker.elastic.co/logstash/logstash:6.1.2
    environment:
      xpack.monitoring.enabled: false
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    links:
    - redis:redis
    volumes_from:
    - logstash-collector-conf
    command:
    - -f
    - /config/logstash.conf
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: logstash-collector-conf
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    environment:
      xpack.monitoring.enabled: false
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
      node.name: $${HOSTNAME}
      discovery.zen.ping.unicast.hosts: es
    stdin_open: true
    tty: true
    volumes_from:
    - es-storage
    labels:
      io.rancher.sidekicks: es-storage
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: elk=false
      io.rancher.scheduler.global: 'true'
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
  redis:
    image: redis:alpine
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    labels:
      io.rancher.container.pull_image: always
  logstash-indexer-conf:
    image: alpine:latest
    working_dir: /config
    volumes:
    - /config
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    links:
    - redis:redis
    - es:es
    command:
    - wget
    - http://rancher-metadata.rancher.internal/latest/self/service/metadata/indexer
    - -O
    - logstash.conf
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.pull_image: always
  sysctl:
    privileged: true
    image: alpine
    stdin_open: true
    network_mode: none
    tty: true
    command:
    - sysctl
    - -w
    - vm.max_map_count=262144
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      cron.schedule: 0 */5 * * * *
      cron.action: start
  cerebro:
    image: yannart/cerebro
    stdin_open: true
    tty: true
    links:
    - es:es
    labels:
      io.rancher.container.pull_image: always
  curator:
    image: python:alpine
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    links:
    - es:es
    volumes_from:
    - curator-conf
    command:
    - sh
    - /config/curator.sh
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.sidekicks: curator-conf
      io.rancher.container.pull_image: always
      cron.schedule: 0 0 * * * *
      cron.action: restart
  logspout:
    image: bekt/logspout-logstash
    environment:
      LOGSPOUT: ignore
      ROUTE_URIS: logstash://logstash-collector:5000
    stdin_open: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    links:
    - logstash-collector:logstash-collector
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  curator-conf:
    image: alpine:latest
    working_dir: /config
    volumes:
    - /config
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    links:
    - es:es
    command:
    - wget
    - http://rancher-metadata.rancher.internal/latest/self/service/metadata/curator
    - -O
    - curator.sh
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.2
    stdin_open: true
    tty: true
    environment:
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    links:
    - es:elasticsearch
    labels:
      io.rancher.container.pull_image: always
  logstash-indexer:
    image: docker.elastic.co/logstash/logstash:6.1.2
    environment:
      xpack.monitoring.enabled: false
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    links:
    - redis:redis
    - es:es
    volumes_from:
    - logstash-indexer-conf
    command:
    - -f
    - /config/logstash.conf
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: logstash-indexer-conf
