# notemplating
version: '2'
catalog:
  name: "ELK"
  version: "6.1.2"
  description: "ELK Monitoring Solution"
  uuid: elk-6-1-2
  minimum_rancher_version: v1.1.99
  questions:
    - variable: ES_JAVA_OPTS
      description: |
        Datanodes ES_JAVA_OPTS
      label: ES_JAVA_OPTS
      type: string
      default: "-Xms512m -Xmx512m"
      required: true
    - variable: ES_STORAGE
      description: |
        volume options
      label: Storage dir
      type: string
      default: "/usr/share/elasticsearch/data"
      required: true
    - variable: collector_conf
      description: |
        generate collect logstash.conf
      label: collect logstash.conf
      type: multiline
      required: true
      default: |
        input {
          udp {
            port => 5000
            codec => "json"
          }
          http {
            port => 8000
            type => "elb-healthcheck"
          }
        }
        output {
          redis {
            host => "redis"
            port => "6379"
            data_type => "list"
            key => "logstash"
          }
        }
    - variable: indexer_conf
      description: |
        generate index logstash.conf
      label: index logstash.conf
      type: multiline
      required: true
      default: |
        input {
          udp {
            port => 5000
            codec => "json"
          }
          http {
            port => 8000
            type => "elb-healthcheck"
          }
          redis {
            host => "redis"
            port => 6379
            threads => 16
            key => "logstash"
            data_type => "list"
            codec => json
            batch_count => 10000
          }
        }
        output {
          elasticsearch {
            hosts => ["es:9200"]
          }
        }
    - variable: curator_config
      description: |
        generate curator config.yml
      label: curator config.yml
      type: multiline
      required: true
      default: |
        client:
          hosts:
            - es
    - variable: curator_delete
      description: |
        generate curator delete.yml
      label: curator delete.yml
      type: multiline
      required: true
      default: |
        actions:
          1:
            action: delete_indices
            filters:
            - filtertype: age
              source: creation_date
              direction: older
              unit: hours
              unit_count: 240
              timestring: '%Y.%m.%d.%H'
            - filtertype: pattern
              kind: regex
              value: 'logstash-*'
    - variable: curator_shell
      description: |
        generate curator curator.sh
      label: curator curator.sh
      type: multiline
      required: true
      default: |
        #!/bin/sh
        pip install elasticsearch-curator
        wget http://rancher-metadata.rancher.internal/latest/self/service/metadata/curator_config -O /curator_config.yml
        wget http://rancher-metadata.rancher.internal/latest/self/service/metadata/curator_delete -O /curator_delete.yml
        curator --config /curator_config.yml /curator_delete.yml


services:
  sysctl:
    start_on_create: true
  cerebro:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  logspout:
    start_on_create: true
  logstash-indexer:
    scale: 2
    metadata:
      indexer: |
        ${indexer_conf}
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  logstash-collector:
    retain_ip: true
    scale: 2
    metadata:
      collector: |
        ${collector_conf}
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  kibana:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5601
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  es:
    scale: 2
    retain_ip: true
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 9200
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreateOnQuorum
      reinitializing_timeout: 60000
  es:
    start_on_create: true
  curator:
    scale: 1
    metadata:
      curator: |
        ${curator_shell}
      curator_config: |
        ${curator_config}
      curator_delete: |
        ${curator_delete}
