version: '2'
services:
  metricbeat-conf:
    image: alpine:latest
    working_dir: /config
    volumes:
    - /config
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    command:
    - sh
    - -c
    - wget http://rancher-metadata.rancher.internal/latest/self/service/metadata/metricbeat -O metricbeat.yml && wget http://rancher-metadata.rancher.internal/latest/self/service/metadata/fields -O fields.yml && chmod 777 -R /config && chmod go-w metricbeat.yml
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label_ne: metricbeat=false
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${METRICBEAT_VERSION}
    network_mode: host
    working_dir: /config
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    command:
    - --system.hostfs=/hostfs
    volumes:
    - /proc:/hostfs/proc:ro
    - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
    - metricbeat-conf
    external_links:
    - ${elasticsearch_link}:elasticsearch
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: metricbeat-conf
      io.rancher.scheduler.affinity:host_label_ne: metricbeat=false
      io.rancher.scheduler.global: 'true'
      io.rancher.container.dns: 'true'
