version: '2'
services:
  metricbeat-conf:
    image: alpine:latest
    working_dir: /config
    volumes:
    - /config
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    command:
    - wget
    - http://rancher-metadata.rancher.internal/latest/self/service/metadata/metricbeat
    - -O
    - metricbeat.yml
    - &&
    - wget
    - http://rancher-metadata.rancher.internal/latest/self/service/metadata/fields
    - -O
    - fields.yml
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.pull_image: always
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${METRICBEAT_VERSION}
    working_dir: /config
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    volumes_from:
    - metricbeat-conf
    external_links:
    - ${elasticsearch_link}:elasticsearch
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: metricbeat-conf
      io.rancher.container.hostname_override: container_name
