version: '2'
services:
  ignite:
    image: apacheignite/ignite:$IGNITE_VERSION
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
    environment:
      CONFIG_URI: http://rancher-metadata.rancher.internal/latest/self/service/metadata/ignite
      OPTION_LIBS: $IGNITE_OPTION_LIBS
      EXTERNAL_LIBS: $IGNITE_EXTERNAL_LIBS
      JVM_OPTS: $IGNITE_JVM_OPTS
