version: '2'
catalog:
  name: "ignite"
  version: "2.3.0"
  description: "Apache Ignite In-Memory Data Fabric is a high-performance"
  uuid: db-2
  minimum_rancher_version: v1.1.99
  questions:
    - variable: IGNITE_VERSION
      description: |
          Ignite version
      label: Ignite version
      type: string
      default: "2.3.0"
    - variable: IGNITE_OPTION_LIBS
      description: |
          Ignite optional libs which will be included in the class path.
      label: IGNITE OPTION_LIBS
      type: string
      default: "ignite-zookeeper,ignite-rest-http"
    - variable: IGNITE_EXTERNAL_LIBS
      description: |
          List of URL's to libs.
      label: IGNITE EXTERNAL_LIBS
      type: string
      default: "https://github.com/mybatis/ignite-cache/releases/download/mybatis-ignite-1.0.5/mybatis-ignite-1.0.5.jar"
    - variable: IGNITE_JVM_OPTS
      description: |
          Environment variables passed to Ignite instance in your docker command.
      label: IGNITE JVM_OPTS
      type: string
      default: "-Xms1g -Xmx1g -server -XX:+AggressiveOpts -XX:MaxPermSize=256m"
      required: true
    - variable: ignite_config
      description: |
        generate config.xml
      label: config.xml
      type: multiline
      required: true
      default: |
        <?xml version="1.0" encoding="UTF-8"?>
        <beans xmlns="http://www.springframework.org/schema/beans" xmlns:cache="http://www.springframework.org/schema/cache" xmlns:context="http://www.springframework.org/schema/context" xmlns:mvc="http://www.springframework.org/schema/mvc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="         http://www.springframework.org/schema/beans         http://www.springframework.org/schema/beans/spring-beans.xsd         http://www.springframework.org/schema/cache         http://www.springframework.org/schema/cache/spring-cache-3.1.xsd         http://www.springframework.org/schema/context         http://www.springframework.org/schema/context/spring-context.xsd ">
           <bean class="org.apache.ignite.configuration.IgniteConfiguration">
              <!-- Enabling Redis. -->
              <property name="connectorConfiguration">
                 <bean class="org.apache.ignite.configuration.ConnectorConfiguration">
                    <property name="port" value="6379" />
                 </bean>
              </property>

              <!-- Enabling Apache Ignite Persistent Store. -->
              <property name="persistentStoreConfiguration">
                  <bean class="org.apache.ignite.configuration.PersistentStoreConfiguration"/>
              </property>
              <property name="cacheConfiguration">
                 <list>
                    <!-- for Redis Partitioned cache example configuration (Atomic mode). -->
                    <bean class="org.apache.ignite.configuration.CacheConfiguration">
                       <property name="name" value="default" />
                       <property name="atomicityMode" value="ATOMIC" />
                       <property name="backups" value="2" />
                    </bean>
                 </list>
              </property>
              <property name="discoverySpi">
                 <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
                    <property name="ipFinder">
                       <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.zk.TcpDiscoveryZookeeperIpFinder">
                          <property name="allowDuplicateRegistrations" value="false" />
                          <property name="basePath" value="/ignite" />
                          <property name="serviceName" value="ignite" />
                          <property name="zkConnectionString" value="zk.zookeeper.rancher.internal:2181" />
                       </bean>
                    </property>
                 </bean>
              </property>
           </bean>
        </beans>
services:
  ignite:
    metadata:
      ignite: |
        ${ignite_config}
    retain_ip: true
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 6379
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
